### PR TITLE
feat: add generics

### PR DESCRIPTION
**Pull request by nolotz**
Hi there,

have here some modifications to reduce type assertions with new generics.

### CODE REVIEW

**Comment by MauriceGit** [comment]
Hey, 
any reason you already closed your pull-request? 
I was planning to implement generics for some time and just didn't get to it yet. So if it works and I am happy with a code-review (and maybe some changes, lets see), we can probably merge this.

**Comment by nolotz** [comment]
Hi @MauriceGit,

It looked like you were not active on this project and I had a few additional changes in mind.

**Comment by MauriceGit** [comment]
Hi, 
I agree, not as active as I would like to be. Life gets in the way... What do you have in mind?
I'll update to modules the next couple of days and could then look into generics. Are you done so far with this particular pull-request/commit?

**Comment by nolotz** [comment]
I'll open the PR again in the next free minute.

**Pull request closed without merging**
